Automated deploys
worldcoin/world-id-contracts pull request #27
Opened 2023-01-04 18:25 UTC by kustosz

With the introduction of semaphore-mtb, getting a running instance of this contract has become quite difficult. This aims to mitigate the problem. Note that downloading the mtb binary doesn't currently work, because the repo still hasn't been opened.

2023-01-05 16:06 UTC, iamrecursion requested changes
A few comments and questions left inline. Some clarification is needed.

Please prettier format the `README`.

2023-01-05 16:06 UTC, iamrecursion commented on scripts/deploy.js
> +async function ensureVeirfierBytecode(plan, config) {
Typo in the name. Please refactor.

2023-01-09 17:50 UTC, kustosz commented on Makefile
> -build:; forge build && node ./src/test/scripts/generate-circom-lib.js
This was generating a sol lib for the contract – unused since the `batching` branch started.

2023-01-09 18:45 UTC, kustosz commented on scripts/deploy.js
> +const DEFAULT_RPC_URL = 'http://localhost:8545'
A whatever – you can use this script for any ETH RPC node. The default is a default for `geth`, but you can use whatever else, depending on the network you want.

2023-01-09 18:52 UTC, iamrecursion approved these changes
Good to go!

2023-01-09 18:53 UTC, merged